In [1]:
#pip install pandas

In [2]:
import pandas as pd

# Series

In [3]:
a=[10,20,30,40]
pd.Series(a)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
b=[2.3,4.5,1.2,5.6]
pd.Series(b)

0    2.3
1    4.5
2    1.2
3    5.6
dtype: float64

In [5]:
c=["s","u","n","d","a","r","i"]
pd.Series(c)

0    s
1    u
2    n
3    d
4    a
5    r
6    i
dtype: str

In [6]:
x=[3+4j,5+6j]
pd.Series(x)

0    3.0+4.0j
1    5.0+6.0j
dtype: complex128

In [7]:
y=[True,False]
pd.Series(y)

0     True
1    False
dtype: bool

# DataFrame

In [8]:
data={"names":[10,20,30,40],
     "attendance":["P","A","A","A"]}
pd.DataFrame(data)

   names attendance
0     10          P
1     20          A
2     30          A
3     40          A

In [9]:
data={"names":["surya","gayee","keeru","deepu"],
      "subjects":["Maths","English","Physics","Chemistry"],
     "marks":[90,80,89,78],
     "percentages":[89.9,78.4,85.5,76.5]}
pd.DataFrame(data)

   names   subjects  marks  percentages
0  surya      Maths     90         89.9
1  gayee    English     80         78.4
2  keeru    Physics     89         85.5
3  deepu  Chemistry     78         76.5

In [10]:
data=pd.read_csv("Student_Report.csv")
data

     Names  Marks Grade
0    Jnana     88     B
1  Tripura     78     B
2  Sundari     90     A
3    Surya     98     A

In [11]:
data.columns

Index(['Names', 'Marks', 'Grade'], dtype='str')

In [12]:
data.shape

(4, 3)

In [13]:
data.info

<bound method DataFrame.info of      Names  Marks Grade
0    Jnana     88     B
1  Tripura     78     B
2  Sundari     90     A
3    Surya     98     A>

In [14]:
data1=pd.read_csv("genz_social_media.csv")
data1

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0,6.705830,Medium,15.779443
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1,6.633111,High,47.714864
2,25,Female,India,2.782420,TikTok,2,Socializing,18.170204,1,6.035397,Medium,62.524625
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1,8.110861,Medium,31.935102
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1,6.658598,Medium,29.466046
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1,7.230186,Medium,66.317438
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1,8.273996,Medium,47.150600
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0,7.611955,Medium,18.872826
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1,2.341113,High,62.136012
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1,5.828090,High,34.892929

In [15]:
data1.head(5)

,age,gender,country,daily_usage_hours,primary_platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0,6.705830,Medium,15.779443
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1,6.633111,High,47.714864
2,25,Female,India,2.782420,TikTok,2,Socializing,18.170204,1,6.035397,Medium,62.524625
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1,8.110861,Medium,31.935102
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1,6.658598,Medium,29.466046

In [16]:
data1.columns

Index(['age', 'gender', 'country', 'daily_usage_hours', 'primary_platform',
       'num_platforms_used', 'purpose', 'avg_session_minutes', 'night_usage',
       'mental_health_score', 'addiction_level', 'screen_time_before_sleep'],
      dtype='str')

In [17]:
data1.shape

(1000000, 12)

In [19]:
data1.info

<bound method DataFrame.info of         age  gender    country  daily_usage_hours primary_platform  \
0        19    Male  Australia           2.658617         Snapchat
1        16  Female        USA           5.685387          Twitter
2        25  Female      India           2.782420           TikTok
3        27    Male      India           3.486598          YouTube
4        23  Female      India           3.748829           TikTok
...     ...     ...        ...                ...              ...
999995   21    Male      India           3.097065         Snapchat
999996   14    Male      India           3.663561        Instagram
999997   20    Male      India           4.474618          YouTube
999998   24  Female    Germany           7.829924          YouTube
999999   13    Male     Canada           5.313645           TikTok

        num_platforms_used           purpose  avg_session_minutes  \
0                        4         Education            29.222443
1                        3       Socializing            32.464726
2                        2       Socializing            18.170204
3                        4         Education            22.493804
4                        1     Entertainment            27.358410
...                    ...               ...                  ...
999995                   4     Entertainment            21.158532
999996                   1         Education            26.312119
999997                   2       Socializing            13.623681
999998                   2  Content Creation            15.789750
999999                   1       Socializing            26.397129

        night_usage  mental_health_score addiction_level  \
0                 0             6.705830          Medium
1                 1             6.633111            High
2                 1             6.035397          Medium
3                 1             8.110861          Medium
4                 1             6.658598          Medium
...             ...                  ...             ...
999995            1             7.230186          Medium
999996            1             8.273996          Medium
999997            0             7.611955          Medium
999998            1             2.341113            High
999999            1             5.828090            High

        screen_time_before_sleep
0                      15.779443
1                      47.714864
2                      62.524625
3                      31.935102
4                      29.466046
...                          ...
999995                 66.317438
999996                 47.150600
999997                 18.872826
999998                 62.136012
999999                 34.892929

[1000000 rows x 12 columns]>